/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v4beta1

import (
	v4beta1 "github.com/jenkins-x/jx-api/v4/pkg/apis/core/v4beta1"
	"github.com/jenkins-x/jx-api/v4/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type CoreV4beta1Interface interface {
	RESTClient() rest.Interface
	EnvironmentsGetter
	PipelineActivitiesGetter
	PluginsGetter
	ReleasesGetter
	SourceRepositoriesGetter
}

// CoreV4beta1Client is used to interact with features provided by the core.jenkins-x.io group.
type CoreV4beta1Client struct {
	restClient rest.Interface
}

func (c *CoreV4beta1Client) Environments(namespace string) EnvironmentInterface {
	return newEnvironments(c, namespace)
}

func (c *CoreV4beta1Client) PipelineActivities(namespace string) PipelineActivityInterface {
	return newPipelineActivities(c, namespace)
}

func (c *CoreV4beta1Client) Plugins(namespace string) PluginInterface {
	return newPlugins(c, namespace)
}

func (c *CoreV4beta1Client) Releases(namespace string) ReleaseInterface {
	return newReleases(c, namespace)
}

func (c *CoreV4beta1Client) SourceRepositories(namespace string) SourceRepositoryInterface {
	return newSourceRepositories(c, namespace)
}

// NewForConfig creates a new CoreV4beta1Client for the given config.
func NewForConfig(c *rest.Config) (*CoreV4beta1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &CoreV4beta1Client{client}, nil
}

// NewForConfigOrDie creates a new CoreV4beta1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CoreV4beta1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new CoreV4beta1Client for the given RESTClient.
func New(c rest.Interface) *CoreV4beta1Client {
	return &CoreV4beta1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v4beta1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CoreV4beta1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
