/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v4beta1

import (
	"context"
	"time"

	v4beta1 "github.com/jenkins-x/jx-api/v4/pkg/apis/jenkins.io/v4beta1"
	scheme "github.com/jenkins-x/jx-api/v4/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CommitStatusesGetter has a method to return a CommitStatusInterface.
// A group's client should implement this interface.
type CommitStatusesGetter interface {
	CommitStatuses(namespace string) CommitStatusInterface
}

// CommitStatusInterface has methods to work with CommitStatus resources.
type CommitStatusInterface interface {
	Create(ctx context.Context, commitStatus *v4beta1.CommitStatus, opts v1.CreateOptions) (*v4beta1.CommitStatus, error)
	Update(ctx context.Context, commitStatus *v4beta1.CommitStatus, opts v1.UpdateOptions) (*v4beta1.CommitStatus, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v4beta1.CommitStatus, error)
	List(ctx context.Context, opts v1.ListOptions) (*v4beta1.CommitStatusList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v4beta1.CommitStatus, err error)
	CommitStatusExpansion
}

// commitStatuses implements CommitStatusInterface
type commitStatuses struct {
	client rest.Interface
	ns     string
}

// newCommitStatuses returns a CommitStatuses
func newCommitStatuses(c *JenkinsV4beta1Client, namespace string) *commitStatuses {
	return &commitStatuses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the commitStatus, and returns the corresponding commitStatus object, and an error if there is any.
func (c *commitStatuses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v4beta1.CommitStatus, err error) {
	result = &v4beta1.CommitStatus{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("commitstatuses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of CommitStatuses that match those selectors.
func (c *commitStatuses) List(ctx context.Context, opts v1.ListOptions) (result *v4beta1.CommitStatusList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v4beta1.CommitStatusList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("commitstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested commitStatuses.
func (c *commitStatuses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("commitstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a commitStatus and creates it.  Returns the server's representation of the commitStatus, and an error, if there is any.
func (c *commitStatuses) Create(ctx context.Context, commitStatus *v4beta1.CommitStatus, opts v1.CreateOptions) (result *v4beta1.CommitStatus, err error) {
	result = &v4beta1.CommitStatus{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("commitstatuses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(commitStatus).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a commitStatus and updates it. Returns the server's representation of the commitStatus, and an error, if there is any.
func (c *commitStatuses) Update(ctx context.Context, commitStatus *v4beta1.CommitStatus, opts v1.UpdateOptions) (result *v4beta1.CommitStatus, err error) {
	result = &v4beta1.CommitStatus{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("commitstatuses").
		Name(commitStatus.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(commitStatus).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the commitStatus and deletes it. Returns an error if one occurs.
func (c *commitStatuses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("commitstatuses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *commitStatuses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("commitstatuses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched commitStatus.
func (c *commitStatuses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v4beta1.CommitStatus, err error) {
	result = &v4beta1.CommitStatus{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("commitstatuses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
