/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v4beta1

import (
	"context"
	time "time"

	jenkinsiov4beta1 "github.com/jenkins-x/jx-api/v4/pkg/apis/jenkins.io/v4beta1"
	versioned "github.com/jenkins-x/jx-api/v4/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jenkins-x/jx-api/v4/pkg/client/informers/externalversions/internalinterfaces"
	v4beta1 "github.com/jenkins-x/jx-api/v4/pkg/client/listers/jenkins.io/v4beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EnvironmentRoleBindingInformer provides access to a shared informer and lister for
// EnvironmentRoleBindings.
type EnvironmentRoleBindingInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v4beta1.EnvironmentRoleBindingLister
}

type environmentRoleBindingInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEnvironmentRoleBindingInformer constructs a new informer for EnvironmentRoleBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEnvironmentRoleBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEnvironmentRoleBindingInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEnvironmentRoleBindingInformer constructs a new informer for EnvironmentRoleBinding type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEnvironmentRoleBindingInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JenkinsV4beta1().EnvironmentRoleBindings(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JenkinsV4beta1().EnvironmentRoleBindings(namespace).Watch(context.TODO(), options)
			},
		},
		&jenkinsiov4beta1.EnvironmentRoleBinding{},
		resyncPeriod,
		indexers,
	)
}

func (f *environmentRoleBindingInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEnvironmentRoleBindingInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *environmentRoleBindingInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&jenkinsiov4beta1.EnvironmentRoleBinding{}, f.defaultInformer)
}

func (f *environmentRoleBindingInformer) Lister() v4beta1.EnvironmentRoleBindingLister {
	return v4beta1.NewEnvironmentRoleBindingLister(f.Informer().GetIndexer())
}
