/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v4beta1 "github.com/jenkins-x/jx-api/v4/pkg/apis/jenkins.io/v4beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGitServices implements GitServiceInterface
type FakeGitServices struct {
	Fake *FakeJenkinsV4beta1
	ns   string
}

var gitservicesResource = schema.GroupVersionResource{Group: "jenkins.io", Version: "v4beta1", Resource: "gitservices"}

var gitservicesKind = schema.GroupVersionKind{Group: "jenkins.io", Version: "v4beta1", Kind: "GitService"}

// Get takes name of the gitService, and returns the corresponding gitService object, and an error if there is any.
func (c *FakeGitServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v4beta1.GitService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gitservicesResource, c.ns, name), &v4beta1.GitService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v4beta1.GitService), err
}

// List takes label and field selectors, and returns the list of GitServices that match those selectors.
func (c *FakeGitServices) List(ctx context.Context, opts v1.ListOptions) (result *v4beta1.GitServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gitservicesResource, gitservicesKind, c.ns, opts), &v4beta1.GitServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v4beta1.GitServiceList{ListMeta: obj.(*v4beta1.GitServiceList).ListMeta}
	for _, item := range obj.(*v4beta1.GitServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gitServices.
func (c *FakeGitServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gitservicesResource, c.ns, opts))

}

// Create takes the representation of a gitService and creates it.  Returns the server's representation of the gitService, and an error, if there is any.
func (c *FakeGitServices) Create(ctx context.Context, gitService *v4beta1.GitService, opts v1.CreateOptions) (result *v4beta1.GitService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gitservicesResource, c.ns, gitService), &v4beta1.GitService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v4beta1.GitService), err
}

// Update takes the representation of a gitService and updates it. Returns the server's representation of the gitService, and an error, if there is any.
func (c *FakeGitServices) Update(ctx context.Context, gitService *v4beta1.GitService, opts v1.UpdateOptions) (result *v4beta1.GitService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gitservicesResource, c.ns, gitService), &v4beta1.GitService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v4beta1.GitService), err
}

// Delete takes name of the gitService and deletes it. Returns an error if one occurs.
func (c *FakeGitServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(gitservicesResource, c.ns, name), &v4beta1.GitService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGitServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gitservicesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v4beta1.GitServiceList{})
	return err
}

// Patch applies the patch and returns the patched gitService.
func (c *FakeGitServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v4beta1.GitService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gitservicesResource, c.ns, name, pt, data, subresources...), &v4beta1.GitService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v4beta1.GitService), err
}
