/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v4beta1 "github.com/jenkins-x/jx-api/v4/pkg/apis/jenkins.io/v4beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSourceRepositoryGroups implements SourceRepositoryGroupInterface
type FakeSourceRepositoryGroups struct {
	Fake *FakeJenkinsV4beta1
	ns   string
}

var sourcerepositorygroupsResource = schema.GroupVersionResource{Group: "jenkins.io", Version: "v4beta1", Resource: "sourcerepositorygroups"}

var sourcerepositorygroupsKind = schema.GroupVersionKind{Group: "jenkins.io", Version: "v4beta1", Kind: "SourceRepositoryGroup"}

// Get takes name of the sourceRepositoryGroup, and returns the corresponding sourceRepositoryGroup object, and an error if there is any.
func (c *FakeSourceRepositoryGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v4beta1.SourceRepositoryGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sourcerepositorygroupsResource, c.ns, name), &v4beta1.SourceRepositoryGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v4beta1.SourceRepositoryGroup), err
}

// List takes label and field selectors, and returns the list of SourceRepositoryGroups that match those selectors.
func (c *FakeSourceRepositoryGroups) List(ctx context.Context, opts v1.ListOptions) (result *v4beta1.SourceRepositoryGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sourcerepositorygroupsResource, sourcerepositorygroupsKind, c.ns, opts), &v4beta1.SourceRepositoryGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v4beta1.SourceRepositoryGroupList{ListMeta: obj.(*v4beta1.SourceRepositoryGroupList).ListMeta}
	for _, item := range obj.(*v4beta1.SourceRepositoryGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sourceRepositoryGroups.
func (c *FakeSourceRepositoryGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sourcerepositorygroupsResource, c.ns, opts))

}

// Create takes the representation of a sourceRepositoryGroup and creates it.  Returns the server's representation of the sourceRepositoryGroup, and an error, if there is any.
func (c *FakeSourceRepositoryGroups) Create(ctx context.Context, sourceRepositoryGroup *v4beta1.SourceRepositoryGroup, opts v1.CreateOptions) (result *v4beta1.SourceRepositoryGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sourcerepositorygroupsResource, c.ns, sourceRepositoryGroup), &v4beta1.SourceRepositoryGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v4beta1.SourceRepositoryGroup), err
}

// Update takes the representation of a sourceRepositoryGroup and updates it. Returns the server's representation of the sourceRepositoryGroup, and an error, if there is any.
func (c *FakeSourceRepositoryGroups) Update(ctx context.Context, sourceRepositoryGroup *v4beta1.SourceRepositoryGroup, opts v1.UpdateOptions) (result *v4beta1.SourceRepositoryGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sourcerepositorygroupsResource, c.ns, sourceRepositoryGroup), &v4beta1.SourceRepositoryGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v4beta1.SourceRepositoryGroup), err
}

// Delete takes name of the sourceRepositoryGroup and deletes it. Returns an error if one occurs.
func (c *FakeSourceRepositoryGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(sourcerepositorygroupsResource, c.ns, name), &v4beta1.SourceRepositoryGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSourceRepositoryGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sourcerepositorygroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v4beta1.SourceRepositoryGroupList{})
	return err
}

// Patch applies the patch and returns the patched sourceRepositoryGroup.
func (c *FakeSourceRepositoryGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v4beta1.SourceRepositoryGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sourcerepositorygroupsResource, c.ns, name, pt, data, subresources...), &v4beta1.SourceRepositoryGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v4beta1.SourceRepositoryGroup), err
}
