// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/jenkins-x/jx-api/pkg/apis/jenkins.io/v1"
	scheme "github.com/jenkins-x/jx-api/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// EnvironmentRoleBindingsGetter has a method to return a EnvironmentRoleBindingInterface.
// A group's client should implement this interface.
type EnvironmentRoleBindingsGetter interface {
	EnvironmentRoleBindings(namespace string) EnvironmentRoleBindingInterface
}

// EnvironmentRoleBindingInterface has methods to work with EnvironmentRoleBinding resources.
type EnvironmentRoleBindingInterface interface {
	Create(ctx context.Context, environmentRoleBinding *v1.EnvironmentRoleBinding, opts metav1.CreateOptions) (*v1.EnvironmentRoleBinding, error)
	Update(ctx context.Context, environmentRoleBinding *v1.EnvironmentRoleBinding, opts metav1.UpdateOptions) (*v1.EnvironmentRoleBinding, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.EnvironmentRoleBinding, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.EnvironmentRoleBindingList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EnvironmentRoleBinding, err error)
	EnvironmentRoleBindingExpansion
}

// environmentRoleBindings implements EnvironmentRoleBindingInterface
type environmentRoleBindings struct {
	client rest.Interface
	ns     string
}

// newEnvironmentRoleBindings returns a EnvironmentRoleBindings
func newEnvironmentRoleBindings(c *JenkinsV1Client, namespace string) *environmentRoleBindings {
	return &environmentRoleBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the environmentRoleBinding, and returns the corresponding environmentRoleBinding object, and an error if there is any.
func (c *environmentRoleBindings) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.EnvironmentRoleBinding, err error) {
	result = &v1.EnvironmentRoleBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("environmentrolebindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of EnvironmentRoleBindings that match those selectors.
func (c *environmentRoleBindings) List(ctx context.Context, opts metav1.ListOptions) (result *v1.EnvironmentRoleBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.EnvironmentRoleBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("environmentrolebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested environmentRoleBindings.
func (c *environmentRoleBindings) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("environmentrolebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a environmentRoleBinding and creates it.  Returns the server's representation of the environmentRoleBinding, and an error, if there is any.
func (c *environmentRoleBindings) Create(ctx context.Context, environmentRoleBinding *v1.EnvironmentRoleBinding, opts metav1.CreateOptions) (result *v1.EnvironmentRoleBinding, err error) {
	result = &v1.EnvironmentRoleBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("environmentrolebindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(environmentRoleBinding).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a environmentRoleBinding and updates it. Returns the server's representation of the environmentRoleBinding, and an error, if there is any.
func (c *environmentRoleBindings) Update(ctx context.Context, environmentRoleBinding *v1.EnvironmentRoleBinding, opts metav1.UpdateOptions) (result *v1.EnvironmentRoleBinding, err error) {
	result = &v1.EnvironmentRoleBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("environmentrolebindings").
		Name(environmentRoleBinding.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(environmentRoleBinding).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the environmentRoleBinding and deletes it. Returns an error if one occurs.
func (c *environmentRoleBindings) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("environmentrolebindings").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *environmentRoleBindings) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("environmentrolebindings").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched environmentRoleBinding.
func (c *environmentRoleBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.EnvironmentRoleBinding, err error) {
	result = &v1.EnvironmentRoleBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("environmentrolebindings").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
