/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/jenkins-x/jx-api/pkg/apis/jenkins.io/v1"
	scheme "github.com/jenkins-x/jx-api/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FactsGetter has a method to return a FactInterface.
// A group's client should implement this interface.
type FactsGetter interface {
	Facts(namespace string) FactInterface
}

// FactInterface has methods to work with Fact resources.
type FactInterface interface {
	Create(ctx context.Context, fact *v1.Fact, opts metav1.CreateOptions) (*v1.Fact, error)
	Update(ctx context.Context, fact *v1.Fact, opts metav1.UpdateOptions) (*v1.Fact, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Fact, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.FactList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Fact, err error)
	FactExpansion
}

// facts implements FactInterface
type facts struct {
	client rest.Interface
	ns     string
}

// newFacts returns a Facts
func newFacts(c *JenkinsV1Client, namespace string) *facts {
	return &facts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the fact, and returns the corresponding fact object, and an error if there is any.
func (c *facts) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Fact, err error) {
	result = &v1.Fact{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("facts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Facts that match those selectors.
func (c *facts) List(ctx context.Context, opts metav1.ListOptions) (result *v1.FactList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.FactList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("facts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested facts.
func (c *facts) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("facts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a fact and creates it.  Returns the server's representation of the fact, and an error, if there is any.
func (c *facts) Create(ctx context.Context, fact *v1.Fact, opts metav1.CreateOptions) (result *v1.Fact, err error) {
	result = &v1.Fact{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("facts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fact).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a fact and updates it. Returns the server's representation of the fact, and an error, if there is any.
func (c *facts) Update(ctx context.Context, fact *v1.Fact, opts metav1.UpdateOptions) (result *v1.Fact, err error) {
	result = &v1.Fact{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("facts").
		Name(fact.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(fact).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the fact and deletes it. Returns an error if one occurs.
func (c *facts) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("facts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *facts) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("facts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched fact.
func (c *facts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Fact, err error) {
	result = &v1.Fact{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("facts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
