/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/jenkins-x/jx-api/pkg/apis/jenkins.io/v1"
	scheme "github.com/jenkins-x/jx-api/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GitServicesGetter has a method to return a GitServiceInterface.
// A group's client should implement this interface.
type GitServicesGetter interface {
	GitServices(namespace string) GitServiceInterface
}

// GitServiceInterface has methods to work with GitService resources.
type GitServiceInterface interface {
	Create(ctx context.Context, gitService *v1.GitService, opts metav1.CreateOptions) (*v1.GitService, error)
	Update(ctx context.Context, gitService *v1.GitService, opts metav1.UpdateOptions) (*v1.GitService, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.GitService, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.GitServiceList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GitService, err error)
	GitServiceExpansion
}

// gitServices implements GitServiceInterface
type gitServices struct {
	client rest.Interface
	ns     string
}

// newGitServices returns a GitServices
func newGitServices(c *JenkinsV1Client, namespace string) *gitServices {
	return &gitServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the gitService, and returns the corresponding gitService object, and an error if there is any.
func (c *gitServices) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.GitService, err error) {
	result = &v1.GitService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gitservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GitServices that match those selectors.
func (c *gitServices) List(ctx context.Context, opts metav1.ListOptions) (result *v1.GitServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.GitServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("gitservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested gitServices.
func (c *gitServices) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("gitservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a gitService and creates it.  Returns the server's representation of the gitService, and an error, if there is any.
func (c *gitServices) Create(ctx context.Context, gitService *v1.GitService, opts metav1.CreateOptions) (result *v1.GitService, err error) {
	result = &v1.GitService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("gitservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gitService).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a gitService and updates it. Returns the server's representation of the gitService, and an error, if there is any.
func (c *gitServices) Update(ctx context.Context, gitService *v1.GitService, opts metav1.UpdateOptions) (result *v1.GitService, err error) {
	result = &v1.GitService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("gitservices").
		Name(gitService.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(gitService).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the gitService and deletes it. Returns an error if one occurs.
func (c *gitServices) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gitservices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *gitServices) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("gitservices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched gitService.
func (c *gitServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.GitService, err error) {
	result = &v1.GitService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("gitservices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
