/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/jenkins-x/jx-api/v3/pkg/apis/jenkins.io/v1"
	scheme "github.com/jenkins-x/jx-api/v3/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PipelineStructuresGetter has a method to return a PipelineStructureInterface.
// A group's client should implement this interface.
type PipelineStructuresGetter interface {
	PipelineStructures(namespace string) PipelineStructureInterface
}

// PipelineStructureInterface has methods to work with PipelineStructure resources.
type PipelineStructureInterface interface {
	Create(ctx context.Context, pipelineStructure *v1.PipelineStructure, opts metav1.CreateOptions) (*v1.PipelineStructure, error)
	Update(ctx context.Context, pipelineStructure *v1.PipelineStructure, opts metav1.UpdateOptions) (*v1.PipelineStructure, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.PipelineStructure, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.PipelineStructureList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.PipelineStructure, err error)
	PipelineStructureExpansion
}

// pipelineStructures implements PipelineStructureInterface
type pipelineStructures struct {
	client rest.Interface
	ns     string
}

// newPipelineStructures returns a PipelineStructures
func newPipelineStructures(c *JenkinsV1Client, namespace string) *pipelineStructures {
	return &pipelineStructures{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the pipelineStructure, and returns the corresponding pipelineStructure object, and an error if there is any.
func (c *pipelineStructures) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.PipelineStructure, err error) {
	result = &v1.PipelineStructure{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipelinestructures").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PipelineStructures that match those selectors.
func (c *pipelineStructures) List(ctx context.Context, opts metav1.ListOptions) (result *v1.PipelineStructureList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.PipelineStructureList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("pipelinestructures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested pipelineStructures.
func (c *pipelineStructures) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("pipelinestructures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a pipelineStructure and creates it.  Returns the server's representation of the pipelineStructure, and an error, if there is any.
func (c *pipelineStructures) Create(ctx context.Context, pipelineStructure *v1.PipelineStructure, opts metav1.CreateOptions) (result *v1.PipelineStructure, err error) {
	result = &v1.PipelineStructure{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("pipelinestructures").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pipelineStructure).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a pipelineStructure and updates it. Returns the server's representation of the pipelineStructure, and an error, if there is any.
func (c *pipelineStructures) Update(ctx context.Context, pipelineStructure *v1.PipelineStructure, opts metav1.UpdateOptions) (result *v1.PipelineStructure, err error) {
	result = &v1.PipelineStructure{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("pipelinestructures").
		Name(pipelineStructure.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(pipelineStructure).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the pipelineStructure and deletes it. Returns an error if one occurs.
func (c *pipelineStructures) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipelinestructures").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *pipelineStructures) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("pipelinestructures").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched pipelineStructure.
func (c *pipelineStructures) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.PipelineStructure, err error) {
	result = &v1.PipelineStructure{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("pipelinestructures").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
