/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

// AppListerExpansion allows custom methods to be added to
// AppLister.
type AppListerExpansion interface{}

// AppNamespaceListerExpansion allows custom methods to be added to
// AppNamespaceLister.
type AppNamespaceListerExpansion interface{}

// BuildPackListerExpansion allows custom methods to be added to
// BuildPackLister.
type BuildPackListerExpansion interface{}

// BuildPackNamespaceListerExpansion allows custom methods to be added to
// BuildPackNamespaceLister.
type BuildPackNamespaceListerExpansion interface{}

// CommitStatusListerExpansion allows custom methods to be added to
// CommitStatusLister.
type CommitStatusListerExpansion interface{}

// CommitStatusNamespaceListerExpansion allows custom methods to be added to
// CommitStatusNamespaceLister.
type CommitStatusNamespaceListerExpansion interface{}

// EnvironmentListerExpansion allows custom methods to be added to
// EnvironmentLister.
type EnvironmentListerExpansion interface{}

// EnvironmentNamespaceListerExpansion allows custom methods to be added to
// EnvironmentNamespaceLister.
type EnvironmentNamespaceListerExpansion interface{}

// EnvironmentRoleBindingListerExpansion allows custom methods to be added to
// EnvironmentRoleBindingLister.
type EnvironmentRoleBindingListerExpansion interface{}

// EnvironmentRoleBindingNamespaceListerExpansion allows custom methods to be added to
// EnvironmentRoleBindingNamespaceLister.
type EnvironmentRoleBindingNamespaceListerExpansion interface{}

// ExtensionListerExpansion allows custom methods to be added to
// ExtensionLister.
type ExtensionListerExpansion interface{}

// ExtensionNamespaceListerExpansion allows custom methods to be added to
// ExtensionNamespaceLister.
type ExtensionNamespaceListerExpansion interface{}

// GitServiceListerExpansion allows custom methods to be added to
// GitServiceLister.
type GitServiceListerExpansion interface{}

// GitServiceNamespaceListerExpansion allows custom methods to be added to
// GitServiceNamespaceLister.
type GitServiceNamespaceListerExpansion interface{}

// PipelineActivityListerExpansion allows custom methods to be added to
// PipelineActivityLister.
type PipelineActivityListerExpansion interface{}

// PipelineActivityNamespaceListerExpansion allows custom methods to be added to
// PipelineActivityNamespaceLister.
type PipelineActivityNamespaceListerExpansion interface{}

// PluginListerExpansion allows custom methods to be added to
// PluginLister.
type PluginListerExpansion interface{}

// PluginNamespaceListerExpansion allows custom methods to be added to
// PluginNamespaceLister.
type PluginNamespaceListerExpansion interface{}

// ReleaseListerExpansion allows custom methods to be added to
// ReleaseLister.
type ReleaseListerExpansion interface{}

// ReleaseNamespaceListerExpansion allows custom methods to be added to
// ReleaseNamespaceLister.
type ReleaseNamespaceListerExpansion interface{}

// SourceRepositoryListerExpansion allows custom methods to be added to
// SourceRepositoryLister.
type SourceRepositoryListerExpansion interface{}

// SourceRepositoryNamespaceListerExpansion allows custom methods to be added to
// SourceRepositoryNamespaceLister.
type SourceRepositoryNamespaceListerExpansion interface{}

// SourceRepositoryGroupListerExpansion allows custom methods to be added to
// SourceRepositoryGroupLister.
type SourceRepositoryGroupListerExpansion interface{}

// SourceRepositoryGroupNamespaceListerExpansion allows custom methods to be added to
// SourceRepositoryGroupNamespaceLister.
type SourceRepositoryGroupNamespaceListerExpansion interface{}

// TeamListerExpansion allows custom methods to be added to
// TeamLister.
type TeamListerExpansion interface{}

// TeamNamespaceListerExpansion allows custom methods to be added to
// TeamNamespaceLister.
type TeamNamespaceListerExpansion interface{}

// UserListerExpansion allows custom methods to be added to
// UserLister.
type UserListerExpansion interface{}

// UserNamespaceListerExpansion allows custom methods to be added to
// UserNamespaceLister.
type UserNamespaceListerExpansion interface{}
