/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

// EnvironmentListerExpansion allows custom methods to be added to
// EnvironmentLister.
type EnvironmentListerExpansion interface{}

// EnvironmentNamespaceListerExpansion allows custom methods to be added to
// EnvironmentNamespaceLister.
type EnvironmentNamespaceListerExpansion interface{}

// PipelineActivityListerExpansion allows custom methods to be added to
// PipelineActivityLister.
type PipelineActivityListerExpansion interface{}

// PipelineActivityNamespaceListerExpansion allows custom methods to be added to
// PipelineActivityNamespaceLister.
type PipelineActivityNamespaceListerExpansion interface{}

// PluginListerExpansion allows custom methods to be added to
// PluginLister.
type PluginListerExpansion interface{}

// PluginNamespaceListerExpansion allows custom methods to be added to
// PluginNamespaceLister.
type PluginNamespaceListerExpansion interface{}

// ReleaseListerExpansion allows custom methods to be added to
// ReleaseLister.
type ReleaseListerExpansion interface{}

// ReleaseNamespaceListerExpansion allows custom methods to be added to
// ReleaseNamespaceLister.
type ReleaseNamespaceListerExpansion interface{}

// SourceRepositoryListerExpansion allows custom methods to be added to
// SourceRepositoryLister.
type SourceRepositoryListerExpansion interface{}

// SourceRepositoryNamespaceListerExpansion allows custom methods to be added to
// SourceRepositoryNamespaceLister.
type SourceRepositoryNamespaceListerExpansion interface{}
