/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	jenkinsiov1 "github.com/jenkins-x/jx-api/v3/pkg/apis/jenkins.io/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeEnvironmentRoleBindings implements EnvironmentRoleBindingInterface
type FakeEnvironmentRoleBindings struct {
	Fake *FakeJenkinsV1
	ns   string
}

var environmentrolebindingsResource = schema.GroupVersionResource{Group: "jenkins.io", Version: "v1", Resource: "environmentrolebindings"}

var environmentrolebindingsKind = schema.GroupVersionKind{Group: "jenkins.io", Version: "v1", Kind: "EnvironmentRoleBinding"}

// Get takes name of the environmentRoleBinding, and returns the corresponding environmentRoleBinding object, and an error if there is any.
func (c *FakeEnvironmentRoleBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *jenkinsiov1.EnvironmentRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(environmentrolebindingsResource, c.ns, name), &jenkinsiov1.EnvironmentRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jenkinsiov1.EnvironmentRoleBinding), err
}

// List takes label and field selectors, and returns the list of EnvironmentRoleBindings that match those selectors.
func (c *FakeEnvironmentRoleBindings) List(ctx context.Context, opts v1.ListOptions) (result *jenkinsiov1.EnvironmentRoleBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(environmentrolebindingsResource, environmentrolebindingsKind, c.ns, opts), &jenkinsiov1.EnvironmentRoleBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &jenkinsiov1.EnvironmentRoleBindingList{ListMeta: obj.(*jenkinsiov1.EnvironmentRoleBindingList).ListMeta}
	for _, item := range obj.(*jenkinsiov1.EnvironmentRoleBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested environmentRoleBindings.
func (c *FakeEnvironmentRoleBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(environmentrolebindingsResource, c.ns, opts))

}

// Create takes the representation of a environmentRoleBinding and creates it.  Returns the server's representation of the environmentRoleBinding, and an error, if there is any.
func (c *FakeEnvironmentRoleBindings) Create(ctx context.Context, environmentRoleBinding *jenkinsiov1.EnvironmentRoleBinding, opts v1.CreateOptions) (result *jenkinsiov1.EnvironmentRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(environmentrolebindingsResource, c.ns, environmentRoleBinding), &jenkinsiov1.EnvironmentRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jenkinsiov1.EnvironmentRoleBinding), err
}

// Update takes the representation of a environmentRoleBinding and updates it. Returns the server's representation of the environmentRoleBinding, and an error, if there is any.
func (c *FakeEnvironmentRoleBindings) Update(ctx context.Context, environmentRoleBinding *jenkinsiov1.EnvironmentRoleBinding, opts v1.UpdateOptions) (result *jenkinsiov1.EnvironmentRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(environmentrolebindingsResource, c.ns, environmentRoleBinding), &jenkinsiov1.EnvironmentRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jenkinsiov1.EnvironmentRoleBinding), err
}

// Delete takes name of the environmentRoleBinding and deletes it. Returns an error if one occurs.
func (c *FakeEnvironmentRoleBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(environmentrolebindingsResource, c.ns, name), &jenkinsiov1.EnvironmentRoleBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEnvironmentRoleBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(environmentrolebindingsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &jenkinsiov1.EnvironmentRoleBindingList{})
	return err
}

// Patch applies the patch and returns the patched environmentRoleBinding.
func (c *FakeEnvironmentRoleBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *jenkinsiov1.EnvironmentRoleBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(environmentrolebindingsResource, c.ns, name, pt, data, subresources...), &jenkinsiov1.EnvironmentRoleBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*jenkinsiov1.EnvironmentRoleBinding), err
}
