// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package config

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Application) DeepCopyInto(out *Application) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Application.
func (in *Application) DeepCopy() *Application {
	if in == nil {
		return nil
	}
	out := new(Application)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationConfig) DeepCopyInto(out *ApplicationConfig) {
	*out = *in
	if in.Applications != nil {
		in, out := &in.Applications, &out.Applications
		*out = make([]Application, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationConfig.
func (in *ApplicationConfig) DeepCopy() *ApplicationConfig {
	if in == nil {
		return nil
	}
	out := new(ApplicationConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoUpdateConfig) DeepCopyInto(out *AutoUpdateConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoUpdateConfig.
func (in *AutoUpdateConfig) DeepCopy() *AutoUpdateConfig {
	if in == nil {
		return nil
	}
	out := new(AutoUpdateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureConfig) DeepCopyInto(out *AzureConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureConfig.
func (in *AzureConfig) DeepCopy() *AzureConfig {
	if in == nil {
		return nil
	}
	out := new(AzureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzureSecretStorageConfigType) DeepCopyInto(out *AzureSecretStorageConfigType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzureSecretStorageConfigType.
func (in *AzureSecretStorageConfigType) DeepCopy() *AzureSecretStorageConfigType {
	if in == nil {
		return nil
	}
	out := new(AzureSecretStorageConfigType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildPackConfig) DeepCopyInto(out *BuildPackConfig) {
	*out = *in
	if in.BuildPackLibrary != nil {
		in, out := &in.BuildPackLibrary, &out.BuildPackLibrary
		*out = new(BuildPackLibrary)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildPackConfig.
func (in *BuildPackConfig) DeepCopy() *BuildPackConfig {
	if in == nil {
		return nil
	}
	out := new(BuildPackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BuildPackLibrary) DeepCopyInto(out *BuildPackLibrary) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BuildPackLibrary.
func (in *BuildPackLibrary) DeepCopy() *BuildPackLibrary {
	if in == nil {
		return nil
	}
	out := new(BuildPackLibrary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConfig) DeepCopyInto(out *ClusterConfig) {
	*out = *in
	if in.AzureConfig != nil {
		in, out := &in.AzureConfig, &out.AzureConfig
		*out = new(AzureConfig)
		**out = **in
	}
	if in.GKEConfig != nil {
		in, out := &in.GKEConfig, &out.GKEConfig
		*out = new(GKEConfig)
		**out = **in
	}
	if in.DevEnvApprovers != nil {
		in, out := &in.DevEnvApprovers, &out.DevEnvApprovers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConfig.
func (in *ClusterConfig) DeepCopy() *ClusterConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvironmentConfig) DeepCopyInto(out *EnvironmentConfig) {
	*out = *in
	out.Ingress = in.Ingress
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvironmentConfig.
func (in *EnvironmentConfig) DeepCopy() *EnvironmentConfig {
	if in == nil {
		return nil
	}
	out := new(EnvironmentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GKEConfig) DeepCopyInto(out *GKEConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GKEConfig.
func (in *GKEConfig) DeepCopy() *GKEConfig {
	if in == nil {
		return nil
	}
	out := new(GKEConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubAppConfig) DeepCopyInto(out *GithubAppConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubAppConfig.
func (in *GithubAppConfig) DeepCopy() *GithubAppConfig {
	if in == nil {
		return nil
	}
	out := new(GithubAppConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressConfig) DeepCopyInto(out *IngressConfig) {
	*out = *in
	out.TLS = in.TLS
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressConfig.
func (in *IngressConfig) DeepCopy() *IngressConfig {
	if in == nil {
		return nil
	}
	out := new(IngressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JxInstallProfile) DeepCopyInto(out *JxInstallProfile) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JxInstallProfile.
func (in *JxInstallProfile) DeepCopy() *JxInstallProfile {
	if in == nil {
		return nil
	}
	out := new(JxInstallProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequirementsConfig) DeepCopyInto(out *RequirementsConfig) {
	*out = *in
	out.AutoUpdate = in.AutoUpdate
	if in.BuildPacks != nil {
		in, out := &in.BuildPacks, &out.BuildPacks
		*out = new(BuildPackConfig)
		(*in).DeepCopyInto(*out)
	}
	in.Cluster.DeepCopyInto(&out.Cluster)
	if in.Environments != nil {
		in, out := &in.Environments, &out.Environments
		*out = make([]EnvironmentConfig, len(*in))
		copy(*out, *in)
	}
	if in.GithubApp != nil {
		in, out := &in.GithubApp, &out.GithubApp
		*out = new(GithubAppConfig)
		**out = **in
	}
	out.Ingress = in.Ingress
	if in.PipelineUser != nil {
		in, out := &in.PipelineUser, &out.PipelineUser
		*out = new(UserNameEmailConfig)
		**out = **in
	}
	out.SecretStorage = in.SecretStorage
	out.Storage = in.Storage
	in.Vault.DeepCopyInto(&out.Vault)
	out.Velero = in.Velero
	out.VersionStream = in.VersionStream
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequirementsConfig.
func (in *RequirementsConfig) DeepCopy() *RequirementsConfig {
	if in == nil {
		return nil
	}
	out := new(RequirementsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RequirementsValues) DeepCopyInto(out *RequirementsValues) {
	*out = *in
	if in.RequirementsConfig != nil {
		in, out := &in.RequirementsConfig, &out.RequirementsConfig
		*out = new(RequirementsConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RequirementsValues.
func (in *RequirementsValues) DeepCopy() *RequirementsValues {
	if in == nil {
		return nil
	}
	out := new(RequirementsValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretStorageConfig) DeepCopyInto(out *SecretStorageConfig) {
	*out = *in
	out.AzureSecretStorageConfig = in.AzureSecretStorageConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretStorageConfig.
func (in *SecretStorageConfig) DeepCopy() *SecretStorageConfig {
	if in == nil {
		return nil
	}
	out := new(SecretStorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	out.Logs = in.Logs
	out.Reports = in.Reports
	out.Repository = in.Repository
	out.Backup = in.Backup
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageEntryConfig) DeepCopyInto(out *StorageEntryConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageEntryConfig.
func (in *StorageEntryConfig) DeepCopy() *StorageEntryConfig {
	if in == nil {
		return nil
	}
	out := new(StorageEntryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserNameEmailConfig) DeepCopyInto(out *UserNameEmailConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserNameEmailConfig.
func (in *UserNameEmailConfig) DeepCopy() *UserNameEmailConfig {
	if in == nil {
		return nil
	}
	out := new(UserNameEmailConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAWSConfig) DeepCopyInto(out *VaultAWSConfig) {
	*out = *in
	out.VaultAWSUnsealConfig = in.VaultAWSUnsealConfig
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAWSConfig.
func (in *VaultAWSConfig) DeepCopy() *VaultAWSConfig {
	if in == nil {
		return nil
	}
	out := new(VaultAWSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAWSUnsealConfig) DeepCopyInto(out *VaultAWSUnsealConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAWSUnsealConfig.
func (in *VaultAWSUnsealConfig) DeepCopy() *VaultAWSUnsealConfig {
	if in == nil {
		return nil
	}
	out := new(VaultAWSUnsealConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAzureConfig) DeepCopyInto(out *VaultAzureConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAzureConfig.
func (in *VaultAzureConfig) DeepCopy() *VaultAzureConfig {
	if in == nil {
		return nil
	}
	out := new(VaultAzureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultConfig) DeepCopyInto(out *VaultConfig) {
	*out = *in
	if in.AWSConfig != nil {
		in, out := &in.AWSConfig, &out.AWSConfig
		*out = new(VaultAWSConfig)
		**out = **in
	}
	if in.AzureConfig != nil {
		in, out := &in.AzureConfig, &out.AzureConfig
		*out = new(VaultAzureConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultConfig.
func (in *VaultConfig) DeepCopy() *VaultConfig {
	if in == nil {
		return nil
	}
	out := new(VaultConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VeleroConfig) DeepCopyInto(out *VeleroConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VeleroConfig.
func (in *VeleroConfig) DeepCopy() *VeleroConfig {
	if in == nil {
		return nil
	}
	out := new(VeleroConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VersionStreamConfig) DeepCopyInto(out *VersionStreamConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VersionStreamConfig.
func (in *VersionStreamConfig) DeepCopy() *VersionStreamConfig {
	if in == nil {
		return nil
	}
	out := new(VersionStreamConfig)
	in.DeepCopyInto(out)
	return out
}
