/*
Copyright 2020 The Jenkins X Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v4beta1

import (
	v4beta1 "github.com/jenkins-x/jx-api/v4/pkg/apis/jenkins.io/v4beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// GitServiceLister helps list GitServices.
// All objects returned here must be treated as read-only.
type GitServiceLister interface {
	// List lists all GitServices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v4beta1.GitService, err error)
	// GitServices returns an object that can list and get GitServices.
	GitServices(namespace string) GitServiceNamespaceLister
	GitServiceListerExpansion
}

// gitServiceLister implements the GitServiceLister interface.
type gitServiceLister struct {
	indexer cache.Indexer
}

// NewGitServiceLister returns a new GitServiceLister.
func NewGitServiceLister(indexer cache.Indexer) GitServiceLister {
	return &gitServiceLister{indexer: indexer}
}

// List lists all GitServices in the indexer.
func (s *gitServiceLister) List(selector labels.Selector) (ret []*v4beta1.GitService, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v4beta1.GitService))
	})
	return ret, err
}

// GitServices returns an object that can list and get GitServices.
func (s *gitServiceLister) GitServices(namespace string) GitServiceNamespaceLister {
	return gitServiceNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// GitServiceNamespaceLister helps list and get GitServices.
// All objects returned here must be treated as read-only.
type GitServiceNamespaceLister interface {
	// List lists all GitServices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v4beta1.GitService, err error)
	// Get retrieves the GitService from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v4beta1.GitService, error)
	GitServiceNamespaceListerExpansion
}

// gitServiceNamespaceLister implements the GitServiceNamespaceLister
// interface.
type gitServiceNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all GitServices in the indexer for a given namespace.
func (s gitServiceNamespaceLister) List(selector labels.Selector) (ret []*v4beta1.GitService, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v4beta1.GitService))
	})
	return ret, err
}

// Get retrieves the GitService from the indexer for a given namespace and name.
func (s gitServiceNamespaceLister) Get(name string) (*v4beta1.GitService, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v4beta1.Resource("gitservice"), name)
	}
	return obj.(*v4beta1.GitService), nil
}
